version: '3.8'

services:
  
  app:
    build: .
    container_name: racoes-e-cia-app
    restart: always
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}
      CLERK_SECRET_KEY: ${CLERK_SECRET_KEY}

